name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: main --> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: master
          github_token: ${{ secrets.ACCESS_TOKEN }}